spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sun_pay
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

hibernate:
  default_batch_fetch_size: 1000

server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true